catalog
catalogKeyClassesAndExample
	"Returns a paragraph or more describing the key classes of your project. You can use Pillar/Pier syntax to layout out the text i.e., ==Code== and - for bullet."
	^ 'SMark uses ==SMarkSuite== as the base class for benchmark suites. To see examples, have a look at its subclasses.

==SMarkHarness== stears the actual execution and reporting. The class comments gives a few more details on the basic usage.'