stone benchmarks
doPerform
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself.
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself.
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself.
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself.
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself.
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself.
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself.
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself.
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself.
	0 perform: #yourself. 0 perform: #yourself. 0 perform: #yourself